### PR TITLE
Run actions on schedule (nightly) and manually

### PR DESCRIPTION
**Pull request by jccurtis**
See title 😄

### CODE REVIEW

**Comment by jccurtis** [comment]
@markbandstra this fixes the issue with the coveralls default branch from earlier. Just needed to reset everything. This also adds nightly builds and manually triggered builds.

**Comment by markbandstra** [comment]
> Just needed to reset everything.

Can you elaborate on this in case we run into the same issue in the future? Is it the addition of `workflow_dispatch:` to `coveralls.yaml`?

**Comment by jccurtis** [comment]
@markbandstra For sure. I needed to login to coveralls.io with my github creds. 

Then I went to repos:

image

Then settings:

image

Then delete at the bottom of the page:

image

Then I went to add repo:

image

Then found becquerel and turned it on. (In the following screenshot it is already on):

image

This purged old coverage info but correctly picked up the default branch (`main`). I think I originally set this up before we changed the default branch. Technically coveralls claims this will be picked up upon a resync in the settings but that did not work for me. This [issue](https://github.com/lemurheavy/coveralls-public/issues/36) details a similar problem.

**Comment by markbandstra** [comment]
@jccurtis Great, thanks for adding that information.

**Review by markbandstra — APPROVED** [review]
Looks great

**Pull request merged**
