### PR TITLE
Add SPEFile presets fields

### LINKED ISSUE #98: SPE file $PRESETS field
Reading the test spectrum (`1110C NAA cave pottery.Spe`) results in these warnings for the `$PRESETS` field:

```bash
Line 16414 unknown:  $PRESETS:
Line 16415 unknown:  Live Time
Line 16416 unknown:  86400
Line 16417 unknown:  0
```

We should added these as metadata of the `Spectrum` object as in  #81.

### PR DESCRIPTION
**Pull request by jccurtis**
Closes #98

The PR adds the `$PRESETS` field to the `Spe` file parser. This field is included in `Spe` files created by the ORTEC Digibase USB devices. This code was originally included in #94 and #107

TODO: 
- [x] Add warning
- [x] Add custom ParserWarning
- [ ] Confirm Travis finishes for `py27`

### CODE REVIEW

**Comment by jccurtis** [comment]
@chunhochow brings up a good point to through a warning

**Comment by markbandstra** [comment]
@jccurtis Please look into the CI build errors.

**Comment by jccurtis** [comment]
@markbandstra @cosama 

Check out the fix I just pushed in 8535870 (no numbers in the hash 😨)

The configuration is from [here](https://docs.pytest.org/en/latest/reference.html#configuration-options). The specific issues is mentioned in an open issue [here](https://github.com/pytest-dev/pytest/issues/2917)

**Comment by jccurtis** [comment]
Weird, I cannot produce the error on Travis locally in `py27`...

**Comment by markbandstra** [comment]
I had to find out: the probability of a 7-digit hash made of only numerals is (10/16)^7 ~ 3.7%.

**Comment by cosama** [comment]
The issue with travis was, the `autocal_test.py` calls `bq.Spectrum.from_file(filename2)` on line 31. As this is not wrapped in a with statement it 'eats away' the warning, and it won't be raised later on. I added a with block there too, so that it is required to raise a warning.

**Comment by jccurtis** [comment]
@markbandstra yes that should be it!

**Comment by jccurtis** [comment]
FYI the pytest folks just patched this behavior. Hopefully the warnings catch will be more robust between py2/3

**Pull request merged**
