### PR TITLE
setup: added pytest-black requirement

### PR DESCRIPTION
**Pull request by arunpersaud**
Setup.cfg has a --black option for tests, which I think needs pytest-black to be installed?

### CODE REVIEW

**Comment by markbandstra** [comment]
Seems to make sense. Did this cause an error for you?

**Comment by markbandstra** [comment]
Alternate solution: read `requirements-dev.txt` in `setup.py` in the same way we currently read `requirements.txt`, and send its contents to `tests_require`. I can work on this.

**Comment by arunpersaud** [comment]
yes, I couldn't run "python3 -m pytest" since it complained about the --black option in setup.cfg

**Comment by markbandstra** [comment]
Not sure the best workflow for making this contribution (could do a PR on your fork I suppose), but what I had in mind to make this PR more futureproof was:

* In `setup.py` add:
```python
with open("requirements-dev.txt", "r") as fh:
    REQUIREMENTS_DEV = fh.read()
```
* In `setup.py` change:
```python
tests_require=["pytest", "pytest-cov", "pytest-black"],
```
to
```python
tests_require=[_f for _f in REQUIREMENTS_DEV.split("\n")[1:] if _f],
```
* Optional: we could remove `flake8` and `pydocstyle` from `requirements-dev.txt` since they're no longer required.

What do you think?

**Comment by arunpersaud** [comment]
sure, I can add this. requirements-dev also seems to include requirements.txt... should that be removed too or parsed out when loading the test-requirements? I'm not that familiar with requirements files

**Comment by markbandstra** [comment]
> sure, I can add this. requirements-dev also seems to include requirements.txt... should that be removed too or parsed out when loading the test-requirements? I'm not that familiar with requirements files

Yes, good point, and my intention was to filter out that line with the `[1:]` in `REQUIREMENTS_DEV.split("\n")[1:]`, so that will return just the packages unique to `requirements-dev.txt`.

**Comment by arunpersaud** [comment]
Just pushed an update. Let me know if this is what you were thinking

**Review by markbandstra — APPROVED** [review]
Perfect, thanks!

**Comment by markbandstra** [comment]
@arunpersaud we've conventionally been letting the person who worked on the PR do the final update and merge commit, so please have a go at this one and #264 . I can also do it if you prefer.

**Pull request merged**
