### PR TITLE
allow **kwargs in Spectrum.fit

### PR DESCRIPTION
**Pull request by jvavrek**
Quickfix: specify `Fitter.fit()` kwargs via `Spectrum.fit()`

### CODE REVIEW

**Comment by markbandstra** [comment]
Please add a test.

**Comment by jvavrek** [comment]
> Please add a test.

Tests added. They caught the fact that I was missing handling the `mask` and `dx` kwargs!

**Comment by jvavrek** [comment]
Now I'm getting `black` formatting mismatches. We need to update the `black` version here!

**Review by markbandstra — APPROVED** [review]

**Comment by jvavrek** [comment]
@markbandstra I snuck in some changes to how flaky tests are handled, but it looks like they were successful!

**Pull request merged**
