### PR TITLE
Fix FWHM formula used by `PeakFilter`

### PR DESCRIPTION
**Pull request by markbandstra**
A user with a keen eye noticed that the `PeakFilter` class has been using an erroneous formula for the spectral energy resolution:

```python
f(x) = np.sqrt(f0 ** 2 + (f1 ** 2 - f0 ** 2) * (x / x1) ** 2)
```

which interpolates between `f(0) = f0` and `f(x1) = f1`, but it scales roughly as `x`, not the intended `sqrt(x)`.

This formula has been changed to

```python
f(x) = np.sqrt(f0 ** 2 + (f1 ** 2 - f0 ** 2) * (x / x1))
```

and the notebook has been brought up to date.

### CODE REVIEW

**Review by jvavrek — APPROVED** [review]
looks good!

**Comment by markbandstra** [comment]
I should also note that this appears to be the only location where this bug crops up. This change may require users to adjust existing code that uses the `autocal` tools, although the `PeakFilter` kernels are pretty robust (which is why we never noticed that problem) so it is also possible that no changes will be needed.

**Comment by jvavrek** [comment]
Ah, autocal tests fail

**Comment by markbandstra** [comment]
Dangit, always run the tests. I'll look into it.

**Review by jvavrek — APPROVED** [review]

**Pull request merged**
