### PR TITLE
Overview notebook

### LINKED ISSUE #94: Overview notebook

### LINKED ISSUE #107: Cleanup quickstart-notebook branch and cherry-pick commits into new branches
The `quickstart-notebook` branch is now a mess of various features which should be cherry-picked onto a different branch (or branches) to clean up/isolate the PR's to merge the features.

I also think this is a VERY good time to move towards a [git-flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) like scheme with use of the `develop` branch. The master branch would then only have PR's for a new release version which we should also start doing.

I will complete this after our meeting on Friday which will require use of this  `quickstart-notebook` branch.

Proposed cherry-picking:

overview-notebook (#137)
- [x] 5a7c787ce346f9c80569a7324ffdf6eeb0047371
- [x] 30a4cd77268740f21259d182abac7169c7ea23e8
- [x] b73388a36b4a42123b22d44d075143aafb6c8739
- [x] b0b3fa0e87f6a731df99f9b89475278816a61298
- [x] 6abf97e9a7bf1c7b86139c1c2c865d0acca2e34a
- [x] 9e3047e3a931c5457978166e4eec97e6224e15be
- [x] 138c38948a9395cd37f9020ce51bc786055fb614
- [x] 0ae396d

spectrum-repr (see #134)
- [x] 05d592d54972218435fba1ad74dfb7d95e6f8227
- [x] 814aee5ac77803632e783d8b396687c1fcac9989
- [x] 2e6c1e718d20dc00f8f580cf97ca2c5eda704b02

spectrum-plot
- NOTE: this was finished by @cosama in #114
- 3997193d1f452d6bcc06c1ffe19cd40da14dfdf5
- 02e8792bdf1e2aafff3ed293feaa1dad598f5e0f

fix-#98 (see #135)
- [x] 24566697e3dbc177cba7f3f9fbc45d5a93bbaafe

fix-#101 (see #136)
- [x] af34b9fdc122f8db1c2bf471c0b80770b6a22c17

### PR DESCRIPTION
**Pull request by jccurtis**
Closes #94 
Closes #107

This PR adds the quickstart notebook which @markbandstra and I wrote to present `bq` as a live demo. The notebook is a bit outdated now with some recent features but should make it into `v0.2.0` with a short mention of all the new features. 

TODO
- [x] Merge #134 
- [x] Merge #135 
- [x] Merge #136
- [x] Update notebook with plotting features from #114
- [x] Update notebook with any rebinning API changes from #78
- [x] Autocal quick demo from #93 
- [ ] Delete branch `quickstart-notebook` upon closing 

Eventually:
- [ ] Fitting tools from #50

### CODE REVIEW

**Comment by cosama** [comment]
About half of the notebooks end with examples the other not. I have no strong opinion either way, but I think it should be consistent. This pull request would be a good place to do so. We can also adjust the rebinning notebook and don't have to do so in #78.

- [ ] Adjust notebook names.

**Comment by markbandstra** [comment]
- [ ] Rename quickstart to overview

**Comment by jccurtis** [comment]
- [ ] Pull in develop to get removal of `PRESETS` warning
- [ ] Add semicolons to plot commands to suppress printing `repr` of `axes` objects

**Comment by jccurtis** [comment]
- [ ] Add the relevant notebook name (or preferably a link) 
- [ ] Remove last notebook (Section `3`) header and add to `README`

**Comment by markbandstra** [comment]
Should I remove the `fitting` notebook? It has been in since c74287c but it doesn't currently work.

**Pull request merged**
