### PR TITLE
Feature GitHub actions

### LINKED ISSUE #216: Github actions
Travis is dropping unlimited support for OSS so lets move to github actions

- [ ] Add github actions workflow

Future work:

- [ ] Add `black` formatting
- [ ] Add CD to pypi

### PR DESCRIPTION
**Pull request by jccurtis**
Closes #216

- [x] Add basic GH actions test workflow
    - [ ] Make required for merge
- [ ] Remove travis CI 
    - [x] Remove config
    - [ ] Remove travis trigger (on https://travis-ci.org/)
    - [ ] Remove required for merge
- [ ] Format with `black`

### CODE REVIEW

**Comment by jccurtis** [comment]
I'd like to run `black` across repo. Currently the tests will fail because the formatting check runs as a part of `pytest`. Thoughts?

**Comment by cosama** [comment]
> I'd like to run `black` across repo. Currently the tests will fail because the formatting check runs as a part of `pytest`. Thoughts?

I would say we pull in `fitting` and `xarray` first and then before merging this we run black on everything and push it. Otherwise you will just end up in a merge conflict hell.

**Comment by jccurtis** [comment]
I'll wait until #146, #211 and #224 are in

**Comment by markbandstra** [comment]
Also drop Python2 (cf. branch [`drop-python2`](https://github.com/lbl-anp/becquerel/tree/drop-python2)).

**Comment by jvavrek** [comment]
> I'll wait until #146, #211 and #224 are in

These are now all merged

**Comment by jccurtis** [comment]
Closing in favor of #242

**Pull request closed without merging**
