### PR TITLE
Fix #96 (NNDC kwargs conflict)

### LINKED ISSUE #96: fetch_wallet_card kwarg overwrite
@markbandstra and I just found a bug with to `nndc.fetch_wallet_card` when specifying `z` and `a_range`. It looks like the `z` kwarg is overwritten

### PR DESCRIPTION
**Pull request by markbandstra**
Minor update to NNDC query API that is transparent to the user, plus added more checks to the NNDC tests. Affects both `fetch_wallet_card` and `fetch_decay_radiation`.

Fixes #96

### CODE REVIEW

**Comment by jccurtis** [comment]
@markbandstra, so in the case of a single query a `DataFrame` is still returned instead of a `Series`?

**Comment by markbandstra** [comment]
Yes, any query always returns a `DataFrame`. Not sure how a `Series` would make sense for mixed data types.

**Comment by jccurtis** [comment]
Thank you! I just wanted to confirm that a `DataFrame` is always returned. What do you think about moving `ufloats_overlap_range` to a general test location since this will likely be useful for other tests?

**Comment by jccurtis** [comment]
Maybe the test helper functions could be located inside `bq.testing`

**Comment by markbandstra** [comment]
We could reorganize `ufloats_overlap_range` but I am not sure if that is needed now. I wrote this function so that a couple of the NNDc tests would pass after I started checking the limits.

**Pull request merged**
