### PR TITLE
Add plot method to EnergyCalBase

### PR DESCRIPTION
**Pull request by jvavrek**
This adds some basic plots:

1. scatter plot of input energy vs input channel
2. line plot of fit energy vs input channel
3. scatter plot of (fit energy - input energy) vs channel

Examples from `energycal.ipynb` below.

This is mostly so one can do a quick `cal.plot()` instead of rewriting a bunch of plotting.

### CODE REVIEW

**Comment by jvavrek** [comment]
From `energycal.ipynb`:

If the calibration has points:

image

If it does not:

image

**Comment by jvavrek** [comment]
@jccurtis @markbandstra hopefully this does not conflict with plans you had for refactoring calibrations, but if it will, let me know!

**Comment by markbandstra** [comment]
> @jccurtis @markbandstra hopefully this does not conflict with plans you had for refactoring calibrations, but if it will, let me know!

No problem, I think it is a good idea and will work it into #245 as it goes forward.

**Review by markbandstra — APPROVED** [review]
Looks good to me

**Pull request merged**
